set -g escape-time 0
set -g mode-keys vi
set -g status-keys vi
set -g history-limit 5000

set-environment -g ZDOTDIR "$HOME"
set -g default-shell /bin/zsh

set -g repeat-time 1000

set-option -g prefix C-q

bind-key h select-pane -L
bind-key l select-pane -R
bind-key k select-pane -U
bind-key j select-pane -D

bind-key -r H resize-pane -L 4
bind-key -r L resize-pane -R 4
bind-key -r K resize-pane -U 4
bind-key -r J resize-pane -D 4

set -g status-right ''

set -g default-terminal "xterm-256color"

set -g pane-border-format "#[align=right]#{pane_title} [#{pane_id}/#{pane_index}]"
set -g pane-border-status top
